export type UtmKeys = keyof typeof labels.utm;
export type ParamsKeys = keyof typeof labels.params;

export const labels = {
  og_image_file: {
    label: "Картинка для превью",
    description: "Картинка для превью",
    type: "string",
    required: true,
    default: "",
    tooltip: "Cоотношение сторон 1,91:1 \n Размер не должен превышать 8 МБ. \n Разрешение от 600 x 315 до 1200 X 630 px.",
    placeholder: "https://",
  },


  sl_name: {
    label: "Уникальное имя",
    description: "Название смартлинка",
    type: "string",
    required: true,
    default: "",
    tooltip: "Уникальное имя — это часть URL-адресаю Например, в ссылке sberbank.com/sms/main именем является main. В том числе имя назначается как аналитический параметр (например, в external_source) для сбора статистики в системах аналитики ClickStream и др.",
    placeholder: "пример: name_abc",
  },
  android_dp: {
    label: "Deeplink или ссылка на страницу сайта",
    description: "Android deep link",
    type: "string",
    required: true,
    default: "",
    tooltip: "Ссылкой для Android может являться deeplink в мобильное приложение, а также URL-адрес (ссылка на страницу сайта), если требуется направить пользователя на сайт",
    placeholder: "пример: android-app://",
  },
  ios_dp: {
    label: "Deeplink или ссылка на страницу сайта",
    description: "iOS deep link",
    type: "string",
    required: true,
    default: "",
    tooltip: "Ссылкой для iOS может являться deeplink в мобильное приложение, а также URL-адрес (ссылка на страницу сайта), если требуется направить пользователя на сайт. В iOS может быть задана последовательность приложений по приоритету.",
    placeholder: "пример: sberbankonline://",
  },
  web_link_desk: {
    label: "Ccылка на страницу сайта",
    description: "Web link desktop",
    type: "string",
    required: true,
    default: "https://www.sberbank.com/ru/person/dist_services/sberbank-online-android",
    tooltip: "Ссылка для Desktop – ссылка на страницу сайта, которая будет использована в случае перехода по ссылке с НЕ Android или iOS устройства.",
    placeholder: "https://",
  },
  need_web_and: {
    label: "Нужен web link для Android",
    description: "Нужен web link для Android",
    type: "boolean",
    required: true,
    default: false,
    tooltip: "",
    placeholder: "",
  },
  need_web_ios: {
    label: "Нужен web link для iOS",
    description: "Нужен web link для iOS",
    type: "boolean",
    required: true,
    default: false,
    tooltip: "",
    placeholder: "",
  },
  web_link_and: {
    name: "web_link_and",
    label: "Ссылка на страницу сайта",
    description: "Ссылка на страницу сайта",
    type: "string",
    required: true,
    default: "",
    tooltip: "В случае отсутствия приложения, пользователь будет перенаправлен на данную страницу сайта, куда будут переданы рекламные источники и пользовательский ID из куки, в get-параметр «cid»",
    placeholder: "",
  },
  web_link_ios: {
    name: "web_link_ios",
    label: "Ссылка на страницу сайта",
    description: "Ссылка на страницу сайта",
    type: "string",
    required: true,
    default: "",
    tooltip: "В случае отсутствия приложения, пользователь будет перенаправлен на данную страницу сайта, куда будут переданы рекламные источники и пользовательский ID из куки, в get-параметр «cid»",
    placeholder: "",
  },
  store_link_and: {
    name: "store_link_and",
    label: "Ссылка в магазин приложений или на страницу сайта",
    description: "Ссылка в магазин приложений или на страницу сайта",
    type: "string",
    required: true,
    default: "",
    tooltip: "В случает отсутствия приложения пользователь будет отправлен в магазин приложений или на страницу сайта для установки приложения.",
    placeholder: "",
  },
  store_link_ios: {
    name: "store_link_ios",
    label: "Ссылка в магазин приложений или на страницу сайта",
    description: "Ссылка в магазин приложений или на страницу сайта",
    type: "string",
    required: true,
    default: "",
    tooltip: "В случает отсутствия приложения пользователь будет отправлен в магазин приложений или на страницу сайта для установки приложения.",
    placeholder: "",
  },
  android_app: {
    label: "Android app",
    description: "Android app",
    type: "string",
    required: true,
    default: "",
    tooltip: "",
    placeholder: "ru.sberbankmobile",
  },
  ios_apps_dp: {
    label: "Deeplink или ссылка на страницу сайта",
    description: "Задайте последовательность приложений iOS",
    type: "string",
    required: true,
    default: "",
    tooltip: "Ссылкой для iOS может являться deeplink в мобильное приложение, а также URL-адрес (ссылка на страницу сайта), если требуется направить пользователя на сайт. В iOS может быть задана последовательность приложений по приоритету.",
    placeholder: "пример: sberbankonline://",
  },
  need_utm: {
    label: "Канал коммуникации",
    openLabel: "Если вы используте UTM-метки выберете, короткая ссылка и добавьте их",
    closedLabel: "Для нескольких источников, добавьте UTM-метки к Смартлинку",
    description: "Укажите канал для аналитики по UTM-меткам",
    default: false,
    type: "boolean",
    tabs: ["sms", "email", "km", "landing","no utm" , "custom"],
    tooltip: "UTM-метки, которые вы укажете в данной форме, будут иметь первый приоритет. Важно! Метки добавленные к диплинкам (UTM-метки и external_source) будут перезаписаны. Указанные в данной форме UTM-метки будут переданы во все ссылки указанные ниже, такое же правило будет действовать для UTM-меток дописанных к Смартлинку и их можно будет увидеть в системах аналитики в соответствующих полях."
    
  },

  utm: {
    tp_utm_source: {
      name: "tp_utm_source",
      label: "utm_source",
      description: "utm_source",
      type: "string",
      required: true,
      default: "",
      tooltip: "",
      placeholder: "utm_source=",
      errorLabel: "utm_source - Ошибка"
    },
    tp_utm_medium: {
      name: "tp_utm_medium",
      label: "utm_medium",
      description: "utm_medium",
      type: "string",
      required: true,
      default: "",
      tooltip: "",
      placeholder: "utm_medium=",
      errorLabel: "utm_medium - Ошибка"
    },
    tp_utm_campaign: {
      name: "tp_utm_campaign",
      label: "utm_campaign",
      description: "utm_campaign",
      type: "string",
      required: true,
      default: "",
      tooltip: "",
      placeholder: "utm_campaign=",
      errorLabel: "utm_campaign - Ошибка"
    },
    tp_utm_content: {
      name: "tp_utm_content",
      label: "utm_content",
      description: "utm_content",
      type: "string",
      required: false,
      default: "",
      tooltip: "",
      placeholder: "utm_content=",
      errorLabel: "utm_content - Ошибка"
    },
    tp_utm_tern: {
      name: "tp_utm_tern",
      label: "utm_tern",
      description: "utm_tern",
      type: "string",
      required: false,
      default: "",
      tooltip: "",
      placeholder: "utm_tern=",
      errorLabel: "utm_tern - Ошибка"
    },
  },
  custom_params: {
    label: "Переданный в Смартлинк get-параметр",
    description: "Переданный в Смартлинк get-параметр",
    type: "boolean",
    required: true,
    default: false,
    tooltip: "В случае, когда переданный в Смартлинк технический get-параметр требуется изменить для разных платформ. Как это работает?Вы заполняете поле «Переданный в Смартлинк get-параметр», а также какое название требуется для других платфор.Логика Смартлинка заменит название get-параметра, сохранив значение",
    placeholder: "",
  },
  params: {
    params_url: {
      name: "params_url",
      label: "params_url",
      description: "params_url",
      type: "string",
      required: true,
      default: "",
      tooltip: "",
      placeholder: "utm_source=",
      errorLabel: "params_url - Ошибка"
    },
    params_web: {
      name: "params_web",
      label: "params_web",
      description: "params_web",
      type: "string",
      required: true,
      default: "",
      tooltip: "",
      placeholder: "utm_source=",
      errorLabel: "params_web - Ошибка"
    },
    params_and: {
      name: "params_and",
      label: "params_and",
      description: "params_and",
      type: "string",
      required: true,
      default: "",
      tooltip: "",
      placeholder: "utm_source=",
      errorLabel: "params_and - Ошибка"
    },
    params_ios: {
      name: "params_ios",
      label: "params_ios",
      description: "params_ios",
      type: "string",
      required: true,
      default: "",
      tooltip: "",
      placeholder: "utm_source=",
      errorLabel: "params_ios - Ошибка"
    },
  },
  pfa: {
    label: "pfa",
    description: "pfa",
    type: "boolean",
    required: true,
    default: false,
    tooltip: "",
    placeholder: "",
  },
  pfa_name: {
    label: "pfa_name",
    description: "pfa_name",
    type: "string",
    required: true,
    default: "",
    tooltip: "",
    placeholder: "external_source",
  },
  multi_app_ios: {
    label: "multi_app_ios",
    description: "Задать последовательность из нескольких приложений iOS",
    type: "boolean",
    required: true,
    default: false,
    tooltip: "",
    placeholder: "",
  },   
} as const
